name: Container Image Build Pipeline
on:
  push:
    branches: [ master ]
    tags:
      - "v*.*.*"
  workflow_dispatch: # Add this section to enable manual triggering

jobs:
  build:
    name: Build ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: tomcat9-jdk17
            context: ./9
            file: 9/9-jdk17/9-jdk17-temurin-ubuntu/Dockerfile
            base_image: tomcat:9-jdk17
            tags: ${{ vars.ALIBABA_CLOUD_CR_HOSTNAME }}/dianplus/tomcat:9-jdk17,${{ vars.ALIBABA_CLOUD_CR_HOSTNAME }}/dianplus/tomcat:9-jdk17-temurin,${{ vars.ALIBABA_CLOUD_CR_HOSTNAME }}/dianplus/tomcat:9-jdk17-temurin-ubuntu
          - name: tomcat9-jre17
            context: ./9
            file: 9/9-jdk17/9-jdk17-temurin-ubuntu/Dockerfile
            base_image: tomcat:9-jre17
            tags: ${{ vars.ALIBABA_CLOUD_CR_HOSTNAME }}/dianplus/tomcat:9-jre17,${{ vars.ALIBABA_CLOUD_CR_HOSTNAME }}/dianplus/tomcat:9-jre17-temurin,${{ vars.ALIBABA_CLOUD_CR_HOSTNAME }}/dianplus/tomcat:9-jre17-temurin-ubuntu
          - name: tomcat9-jdk21
            context: ./9
            file: 9/9-jdk21/9-jdk21-temurin-ubuntu/Dockerfile
            base_image: tomcat:9-jdk21
            tags: ${{ vars.ALIBABA_CLOUD_CR_HOSTNAME }}/dianplus/tomcat:9-jdk21
          - name: tomcat9-jre21
            context: ./9
            file: 9/9-jdk21/9-jdk21-temurin-ubuntu/Dockerfile
            base_image: tomcat:9-jre21
            tags: ${{ vars.ALIBABA_CLOUD_CR_HOSTNAME }}/dianplus/tomcat:9-jre21
          - name: tomcat9-jdk25
            context: ./9
            file: 9/9-jdk25/9-jdk25-temurin-ubuntu/Dockerfile
            base_image: tomcat:9-jdk25
            tags: ${{ vars.ALIBABA_CLOUD_CR_HOSTNAME }}/dianplus/tomcat:9-jdk25
          - name: tomcat9-jre25
            context: ./9
            file: 9/9-jdk25/9-jdk25-temurin-ubuntu/Dockerfile
            base_image: tomcat:9-jre25
            tags: ${{ vars.ALIBABA_CLOUD_CR_HOSTNAME }}/dianplus/tomcat:9-jre25
          - name: tomcat10-jdk21
            context: ./10
            file: 10/10-jdk21/10-jdk21-temurin-ubuntu/Dockerfile
            base_image: tomcat:10-jdk21
            tags: ${{ vars.ALIBABA_CLOUD_CR_HOSTNAME }}/dianplus/tomcat:10-jdk21,${{ vars.ALIBABA_CLOUD_CR_HOSTNAME }}/dianplus/tomcat:10-jdk21-temurin,${{ vars.ALIBABA_CLOUD_CR_HOSTNAME }}/dianplus/tomcat:10-jdk21-temurin-ubuntu
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Log in to Private Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v4
        with:
          registry: ${{ vars.ALIBABA_CLOUD_CR_HOSTNAME }}
          username: ${{ secrets.ALIBABA_CLOUD_CR_USERNAME }}
          password: ${{ secrets.ALIBABA_CLOUD_CR_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v7
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          build-args: |
            BASE_IMAGE=${{ matrix.base_image }}
          platforms: "linux/amd64,linux/arm64"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ matrix.tags }}
